name: Scan code security advisories
description: Scan Haskell code for possible security advisories.

inputs:
  path:
    description: Path of file or directory that will be scanned.
    required: false
    default: .
  token:
    description: Access token to fetch the repository and write the code scanning results from github-action-scan to GitHub code scanning.
    required: false
    default: ${{ github.token }}
  repository:
    description: The name of the repository without the .git extension. The name is not case sensitive.
    required: false
    default: ${{ github.repository }}
  ref:
    description: The full Git reference, formatted as refs/heads/<branch name>, refs/tags/<tag>, refs/pull/<number>/merge, or refs/pull/<number>/head.
    required: false
    default: ${{ github.ref }}
  commitSha:
    description: The SHA of the commit to which the analysis you are uploading relates.
    required: false
    default: ${{ github.sha }}

outputs:
  sarif-id:
    description: The ID of the uploaded SARIF file.
    value: ${{ steps.upload-sarif.outputs.sarif-id }}

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v4
      with:
        repo: blackheaven/haskell-security-action
        name: github-action-scan
    - name: Extract
      shell: bash
      run: |
        docker pull ghcr.io/blackheaven/haskell-security-action
        docker create --name dummy blackheaven/haskell-security-action
        docker cp -L dummy:/bin/github-action-scan github-action-scan
        docker rm -f dummy
    - name: Run Haskell Security Action
      shell: bash
      run: |
        ./github-action-scan \
          --token ${{ inputs.token }} \
          --owner-repository ${{ inputs.repository }} \
          --ref ${{ inputs.ref }} \
          --commit-sha ${{ inputs.commitSha }}

branding:
  icon: 'search'
  color: 'purple'
