name: "CI"
on:
  pull_request:
  push:
  create:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          system-features = nixos-test benchmark big-parallel kvm
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: docker/setup-buildx-action@v2
    - run: nix build -L
    - run: nix build -L '.#packages.x86_64-linux.github-action-scan-image'
    - run: nix flake check
    - name: Extract tag name
      shell: bash
      run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF##*/})"
      id: extract_tag
    - run: nix build -L '.#packages.x86_64-linux.github-action-scan-image'
    - run: docker load -i result
    - name: Log in to the Container registry
      if: startsWith(github.ref, 'refs/tags/v')
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: docker tag blackheaven/haskell-security-action ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.extract_tag.outputs.tag }}
      if: startsWith(github.ref, 'refs/tags/v')
    - run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.extract_tag.outputs.tag }}
      if: startsWith(github.ref, 'refs/tags/v')
